# Generated by Django 5.0.1 on 2024-01-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_author_registerdate_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('replydate', models.DateTimeField(auto_now_add=True)),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.author')),
            ],
        ),
    ]
