# Generated by Django 5.0.1 on 2024-01-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
