# Generated by Django 5.0.1 on 2024-01-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user1',
        ),
    ]
