# Generated by Django 5.0.1 on 2024-01-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_user_author_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user1',
            new_name='user',
        ),
    ]
