# Generated by Django 5.0.1 on 2024-01-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_user1_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
