# Generated by Django 5.0.1 on 2024-01-31 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userpictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='home.author')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
