# Generated by Django 5.0.1 on 2024-01-31 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
