# Generated by Django 5.0.1 on 2024-01-31 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reply_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='uye',
            new_name='user',
        ),
    ]
